### ISSUE TITLE
No VPK is being created

### ISSUE THREAD

**Issue by MDashK** [MisterSheeple/Sonic-Mania-Vita-Build-Guide#1]
Opening a issue request in hope of acquiring some assistance.

Upon following the guide, using the automatic .sh file, the Game.suprx file is created, but no VPK is build or present in the documented directory.

During build, the following warning is displayed:

https://cdn.discordapp.com/attachments/601683789655179266/1010181152667082833/unknown.png

This screenshot presents the present files in the directory in question, after the script finishes:

https://cdn.discordapp.com/attachments/601683789655179266/1010185759342473287/unknown.png

![image](https://user-images.githubusercontent.com/20628551/185716695-880543c4-4cc3-473f-b68c-74b325329ffa.png)

**Comment by MisterSheeple** [comment]
This may be a bug with the Mania-Vita repo itself, but I'll look into it anyway

**Comment by MisterSheeple** [comment]
It builds fine for me.

**Comment by MisterSheeple** [comment]
I'm going to close this because it is ultimately not an issue with the script or guide. If you need any further help fixing this, reach out to me @MisterSheeple#0321 on Discord and I'll do what I can to help.
