### ISSUE TITLE
Sonic Mania Plus

### ISSUE THREAD

**Issue by MysticAx0lotl** [MisterSheeple/Sonic-Mania-Vita-Build-Guide#2]
Hey there!
What should I add to the quickbuild script to make it build Sonic Mania Plus? Thanks!

**Comment by MisterSheeple** [comment]
The script allows you to build Mania Plus by default. No changes are necessary.

**Comment by MysticAx0lotl** [comment]
> The script allows you to build Mania Plus by default. No changes are necessary.

The game still booted into regular Sonic Mania though

**Comment by MysticAx0lotl** [comment]
No VPK was output when I used the script, only the game.suprx. Could that have something to do with it?

**Comment by MisterSheeple** [comment]
Probably. Ask the port's developer.

**Comment by MysticAx0lotl** [comment]
> Probably. Ask the port's developer.

He kind of hates me for no reason whatsoever.

**Comment by MisterSheeple** [comment]
I didn't develop the port, so I can't help you with this. Sorry.

**Comment by MysticAx0lotl** [comment]
> > Probably. Ask the port's developer.
> 
> He kind of hates me for no reason whatsoever.

Man, I was such an edgelord back then 😂
